profile: !ENV ${PROFILE}

selenium:
  page_load_seconds_timeout: 30
  products_basic_info_get_request_seconds_timeout: 60

groceries_homepage:
  url: "https://www.target.com/c/grocery/-/N-5xt1a"
  categories_container:
    css_selector: "[data-test='@web/slingshot-components/bubcat']"
    categories_button_appended_css_selector: " button"
    categories_element_appended_css_selector: " li"
    categories_name_container_appended_css_selector: " [data-test='bubcatItemTitleComponent'] span"

products_website:
  paginator:
    css_selector: "[data-test='pagination']"
    number_of_pages_element_appended_css_selector: " button > span:first-child"
    next_page_element_appended_css_selector: " button[aria-label='next page']"

  product_html_container:
    css_selector: "[data-test='@web/site-top-of-funnel/ProductCardWrapper']"
    product_title_html_anchor_css_selector: "[data-test='product-title']"
    product_url_html_anchor_css_selector: "[data-test] a"
    product_image_html_img_css_selector: "[data-test] img"


  max_number_of_products_to_fetch_via_GET_request: 28
  
  # Set max at offset value in queries to Target's website
  # https://redsky.target.com/redsky_aggregations/v1/web/plp_search_v2,
  # due to such company limiting themselves the amount of products
  # displayed in their paginated websites of products, for example
  # in https://www.target.com/c/bulk-pantry/-/N-gev3n .
  max_offset_value_accepted_by_Target_API: 1199

aws:
  region: !ENV ${AWS_REGION}
  access_key_id: !ENV ${ACCESS_KEY_ID}
  access_key_secret: !ENV ${ACCESS_KEY_SECRET}

  s3_bucket_name: !ENV ${S3_BUCKET_NAME}
